### ISSUE TITLE
Overlay tiles are lost at high zoom

### ISSUE THREAD

**Issue by mr-voleybolist** [2gis/iOS-SDKs-for-tiles#1]
This problem is seen on iOS 13 and above. The map disappears with at high zoom and remains the grid only.

**Comment by teanet** [comment]
Can you provide location? As far as I know we doesn't support all territories.

**Comment by mr-voleybolist** [comment]
Moscow

**Comment by teanet** [comment]
found out that we only support 1-18 zoom levels. Other zoom levels will not be supported

**Comment by teanet** [comment]
Also you can try https://github.com/2gis/MapGL-iOS
there is no zoom level limit
