### ISSUE TITLE
Russia Tiles problem

### ISSUE THREAD

**Issue by dancoderpack** [2gis/iOS-SDKs-for-tiles#2]
<img width="420" alt="Снимок экрана 2020-06-21 в 21 51 33" src="https://user-images.githubusercontent.com/47087795/85232664-6165fa80-b409-11ea-9920-19ea2d8aaf0b.png">

**Comment by teanet** [comment]
yes, we have a problem with our tile server, will fix it asap.
try to use non retina tiles for now

**Comment by teanet** [comment]
I've update tile server url for new one, please check.

**Comment by dancoderpack** [comment]
Thanks! Great work!
